// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Suporte",
            "email": "lbritogit@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/transactions": {
            "get": {
                "description": "Retorna todas as transações ordenadas pela data de criação (mais recentes primeiro).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Lista as transações",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Transaction"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno ao buscar transações",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Registra uma nova transação financeira. O campo \"tipo\" deve ser \"receita\" ou \"despesa\".",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Cria uma transação",
                "parameters": [
                    {
                        "description": "Dados da transação",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.TransactionInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Transaction"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro interno ao salvar a transação",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Transaction": {
            "type": "object",
            "properties": {
                "data_criacao": {
                    "type": "string",
                    "example": "2026-06-23T16:00:00Z"
                },
                "descricao": {
                    "type": "string",
                    "example": "Salário"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "tipo": {
                    "type": "string",
                    "enum": [
                        "receita",
                        "despesa"
                    ],
                    "example": "receita"
                },
                "usuario_id": {
                    "type": "integer",
                    "example": 42
                },
                "valor": {
                    "type": "number",
                    "example": 1500.5
                }
            }
        },
        "main.TransactionInput": {
            "type": "object",
            "properties": {
                "descricao": {
                    "type": "string",
                    "example": "Salário"
                },
                "tipo": {
                    "type": "string",
                    "enum": [
                        "receita",
                        "despesa"
                    ],
                    "example": "receita"
                },
                "usuario_id": {
                    "type": "integer",
                    "example": 42
                },
                "valor": {
                    "type": "number",
                    "example": 1500.5
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Transactions API",
	Description:      "API para gerenciamento de transações financeiras (receitas e despesas).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
